### ISSUE TITLE
BUG: ElasticMaker breaks when fitting tensor

### ISSUE THREAD

**Issue by katnykiel** [materialsproject/atomate2#607]
**Describe the bug**
When I run the following code to calculate elastic constants with VASP:

```python

# Symmetrize the structure
sga = SpacegroupAnalyzer(struct)
struct = sga.get_primitive_standard_structure()

# Get the elastic constants
elastic_flow = ElasticMaker().make(struct)

# Add the workflow to the launchpad
wf = flow_to_workflow(elastic_flow)
lpad.add_wf(wf)
```

I then run `qlaunch rapidfire` and get the following error in the "fit_elastic_tensor" FireWork:

```zsh
Traceback (most recent call last):
  File "/home/knykiel/.conda/envs/2022.10-py39/atomate2/lib/python3.9/site-packages/fireworks/core/rocket.py", line 261, in run
    m_action = t.run_task(my_spec)
  File "/home/knykiel/.conda/envs/2022.10-py39/atomate2/lib/python3.9/site-packages/jobflow/managers/fireworks.py", line 177, in run_task
    response = job.run(store=store)
  File "/home/knykiel/.conda/envs/2022.10-py39/atomate2/lib/python3.9/site-packages/jobflow/core/job.py", line 572, in run
    self.resolve_args(store=store)
  File "/home/knykiel/.conda/envs/2022.10-py39/atomate2/lib/python3.9/site-packages/jobflow/core/job.py", line 678, in resolve_args
    resolved_args = find_and_resolve_references(
  File "/home/knykiel/.conda/envs/2022.10-py39/atomate2/lib/python3.9/site-packages/jobflow/core/reference.py", line 458, in find_and_resolve_references
    resolved_references = resolve_references(
  File "/home/knykiel/.conda/envs/2022.10-py39/atomate2/lib/python3.9/site-packages/jobflow/core/reference.py", line 348, in resolve_references
    cache[uuid][index] = store.get_output(
  File "/home/knykiel/.conda/envs/2022.10-py39/atomate2/lib/python3.9/site-packages/jobflow/core/store.py", line 521, in get_output
    return find_and_resolve_references(
  File "/home/knykiel/.conda/envs/2022.10-py39/atomate2/lib/python3.9/site-packages/jobflow/core/reference.py", line 458, in find_and_resolve_references
    resolved_references = resolve_references(
  File "/home/knykiel/.conda/envs/2022.10-py39/atomate2/lib/python3.9/site-packages/jobflow/core/reference.py", line 353, in resolve_references
    resolved_references[ref] = ref.resolve(
  File "/home/knykiel/.conda/envs/2022.10-py39/atomate2/lib/python3.9/site-packages/jobflow/core/reference.py", line 178, in resolve
    data = MontyDecoder().process_decoded(data)
  File "/home/knykiel/.conda/envs/2022.10-py39/atomate2/lib/python3.9/site-packages/monty/json.py", line 485, in process_decoded
    return cls_(**d)
  File "/home/knykiel/.conda/envs/2022.10-py39/atomate2/lib/python3.9/site-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for TaskDoc
transformations
  Input should be a valid dictionary [type=dict_type, input_value=<pymatgen.alchemy.materia...bject at 0x14be3dd98a30>, input_type=TransformedStructure]
    For further information visit https://errors.pydantic.dev/2.4/v/dict_type
```

All other FireWorks in this workflow (including deformations) return no errors, it is just this final fit_elastic_tensor FireWork.

**To Reproduce**
1. Create ElasticMaker workflow and add to launchpad
2. `qlaunch rapidfire`
3. All FireWorks complete except for "fit_elastic_tensor", which fizzles

I tried running again with a simple Si structure, and this also returned the same error.

**Comment by JaGeo** [comment]
Thank you for reporting this.
Could you update the emmet version and try again? For me, this fixed the bug.

**Comment by katnykiel** [comment]
Thanks for the quick response! I updated emmet with `pip install --upgrade emmet-core` and tried rerunning the fizzled firework, but this yielded the same error. 

When I then tried to submit a new workflow, I received a different error:

```zsh
Traceback (most recent call last):
  File "/home/knykiel/projects/mxene-nlc/elastic-workflow.py", line 8, in <module>
    from atomate2.vasp.flows.core import DoubleRelaxMaker
  File "/home/knykiel/.conda/envs/2022.10-py39/atomate2/lib/python3.9/site-packages/atomate2/vasp/flows/core.py", line 9, in <module>
    from emmet.core.vasp.calculation import VaspObject
  File "/home/knykiel/.conda/envs/2022.10-py39/atomate2/lib/python3.9/site-packages/emmet/core/vasp/calculation.py", line 562, in <module>
    class Calculation(BaseModel):
  File "/home/knykiel/.conda/envs/2022.10-py39/atomate2/lib/python3.9/site-packages/emmet/core/vasp/calculation.py", line 617, in Calculation
    run_ddec6: bool | str = False,
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```

I fixed this by changing `run_ddec6: bool | str = False` to `run_ddec6: Union[bool, str] = False`. I'm running the new workflow now, will update when it completes.

**Comment by JaGeo** [comment]
This bug is new then... Oof. Please let me know if it works. I will update emmet via pull request if needed

**Comment by katnykiel** [comment]
The ElasticMaker workflow still crashed on the same `fit_elastic_tensor` step. I'll keep debugging today and try to find a solution.

**Comment by JaGeo** [comment]
Could you also try to update jobflow?

**Comment by JaGeo** [comment]
@utf @gpetretto any ideas?

**Comment by katnykiel** [comment]
> Could you also try to update jobflow?

I believe I was already using the latest version (0.1.14)

**Comment by JaGeo** [comment]
Could you test the current branch?

**Comment by gpetretto** [comment]
I am pretty confident this is again related to https://github.com/materialsproject/emmet/issues/879.
Based on the error message, it is probably this field that fails to be validated by pydantic:
https://github.com/materialsproject/emmet/blob/d156c41279e3c4a5e25b118df47de54e1488a21a/emmet-core/emmet/core/tasks.py#L379
Again, the problem is that a field is declared as a dictionary but it contains the fully serialized version of an MSONAble object.
In the case of a deformation in the elastic flow the `TaskDoc` apparently contains
```json
"transformations": {
  "@module": "pymatgen.alchemy.materials",
  "@class": "TransformedStructure",
  "lattice": {
 ...
}
```
which is deserialized and then does not match the `dict` type in the `TaskDoc`.
If you want to cross check you can try to downgrade monty and try running again the fit_elastic_tensor Job.

In this case it can probably be fixed by making `transformations = Union[dict,TransformedStructure]` in emmet. 

However, I did not realize there were several fields defined as simple dictionaries but containing the direct serialization of MSONable objects. Sorry for that. At this point I am not sure if it would be better to fix all the fields that may share this same issue, or try to modify again the deserialization so that it avoids them entirely.

**Comment by katnykiel** [comment]
Thanks y'all for the help. Unfortunately, the error still persists. I updated my emmet installation (`/home/knykiel/.conda/envs/2022.10-py39/atomate2/lib/python3.9/site-packages/emmet/core/tasks.py`) in line 379 to be the following:

```python
transformations: Optional[Union[dict,TransformedStructure]] = Field(
    None,
    description="Information on the structural transformations, parsed from a "
    "transformations.json file",
    )
```

I also tried installing the main branch of jobflow using `pip install git+https://github.com/materialsproject/jobflow.git`.

Each time after making these changes and re-running the `fit_elastic_tensor` firework, the job breaks with the same error (see first message). I have even tried re-submitting the entire ElasticMaker workflow, still with no luck. 

I have some time today to work on this, so I will try to identify a solution/workaround.

**Comment by katnykiel** [comment]
> ```python
> transformations: Optional[Union[dict,TransformedStructure]] = Field(
>     None,
>     description="Information on the structural transformations, parsed from a "
>     "transformations.json file",
>     )
> ```
> 

This solution worked for me - I wasn't correctly importing the TransformedStructure object in my last comment. Thank you!

**Comment by JaGeo** [comment]
> However, I did not realize there were several fields defined as simple dictionaries but containing the direct serialization of MSONable objects. Sorry for that. At this point I am not sure if it would be better to fix all the fields that may share this same issue, or try to modify again the deserialization so that it avoids them entirely.

@gpetretto I think it is probably better to modify the deserialization again as these errors will not show up in emmet but later in atomate2 and are nearly impossible to catch without integration tests.

@utf, any opinion?

**Comment by utf** [comment]
Can we catch these by testing for more example calculations in emmet? It does seem like having that deserialisation is useful in general, so it would be a shame to lose it.

**Comment by JaGeo** [comment]
I think the issue is that some properties are read in as a dict with cls=None in loadfn. This will always lead to a failure when the deserialization happens. We could replace dict with Any in such a case but not sure future developers will understand this.

**Comment by utf** [comment]
Ah ok. If I'm understanding correctly, it seems like the problem is fixed if we specify either dict or the object that could be deserialised. In that case, it might be best to support both options and be explicit about the typing?

**Comment by JaGeo** [comment]
Yeah, but would lead maybe to new dependencies in emmet just for types

**Comment by gpetretto** [comment]
Yes, specifying the fields as `Union[dict, SomeMSONableObject]` should always solve this kind of issue. However, as Janine mentioned, this might need to either add new dependencies or resort to `Any` as a type. Which I think is fine, but not very nice. 

The fact is that this error can happen only in a very specific case: when the field is defined only as a dictionary. My idea was to update the deserialization here https://github.com/materialsvirtuallab/monty/blob/5d37679e1f0cd58a8d165d76f3a095cb71266831/monty/json.py#L519 to check the type of the field, and, if it is a `dict`, don't deserialize the whole dictionary but just its values. This should solve the issue in general. The problem that I could not solve properly is finding a reliable way to determine if the field type is dictionary or not. Of course this is easy if limiting the search to `dict` or `Dict` types, or even cases like `Optional[dict]` or `Union[dict, Structure]`. However, when you start to consider all the possible combinations of types things become more complicated.  

Do you have any better idea? Otherwise I can open a PR in monty with what I have implemented so far and check if you have improvements to propose.

**Comment by utf** [comment]
Personally I think we just accept the extra dependencies. At the end of the day, if it is realistic that a certain object could end up in an emmet model, then this should be part of the tests in emmet.

**Comment by utf** [comment]
Do you know if this bug is also the source of #616?

**Comment by nhew1994** [comment]
I had the same issue. Adding in /storage/home/njh5724/.conda/envs/atomate2/lib/python3.9/site-packages/emmet/core/tasks.py:

from pymatgen.alchemy.materials import TransformedStructure 

    )
    transformations: Optional[Union[dict,TransformedStructure]] = Field(
    None,
    description="Information on the structural transformations, parsed from a "
    "transformations.json file",
    )
  
Fixed the issue for me as well. Currently using:
monty==2023.11.3
emmet-core==0.74.2
pydantic==2.4.2

**Comment by katnykiel** [comment]
### issue

I have been encountering more issues while using the ElasticMaker workflow; specifically, in the `fit_elastic_tensor` firework. All previous fireworks in this workflow complete without error. 

The fit_elastic_tensor firework results in one of the possible outcomes;

  1. completes (after ~1 hr), with the following warning:

```
/home/knykiel/.conda/envs/2022.10-py39/atomate2/lib/python3.9/site-packages/pymatgen/core/tensors.py:327: UserWarning: Tensor is not symmetric, information may be lost in voigt conversion.
  warnings.warn("Tensor is not symmetric, information may be lost in voigt conversion.")
```
  2. runs until it reaches job wall time (~4 hrs)
  
  3. fizzles and returns the following error:

```zsh
Traceback (most recent call last):
  File \"/home/knykiel/.conda/envs/2022.10-py39/atomate2/lib/python3.9/site-packages/fireworks/core/rocket.py\", line 261, in run
    m_action = t.run_task(my_spec)
  File \"/home/knykiel/.conda/envs/2022.10-py39/atomate2/lib/python3.9/site-packages/jobflow/managers/fireworks.py\", line 177, in run_task
    response = job.run(store=store)
  File \"/home/knykiel/.conda/envs/2022.10-py39/atomate2/lib/python3.9/site-packages/jobflow/core/job.py\", line 583, in run
    response = function(*self.function_args, **self.function_kwargs)
  File \"/home/knykiel/.conda/envs/2022.10-py39/atomate2/lib/python3.9/site-packages/atomate2/common/jobs/elastic.py\", line 220, in fit_elastic_tensor
    return ElasticDocument.from_stresses(
      File \"/home/knykiel/.conda/envs/2022.10-py39/atomate2/lib/python3.9/site-packages/atomate2/common/schemas/elastic.py\", line 220, in from_stresses
    derived_properties = DerivedProperties(**property_dict)
  File \"/home/knykiel/.conda/envs/2022.10-py39/atomate2/lib/python3.9/site-packages/pydantic/main.py\", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 7 validation errors for DerivedProperties
trans_v
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.4/v/float_type
long_v
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.4/v/float_type
snyder_ac
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.4/v/float_type
snyder_opt
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.4/v/float_type
snyder_total
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.4/v/float_type
cahill_thermalcond
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.4/v/float_type
debye_temperature
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.4/v/float_type
```

I have tried BaseVaspMaker and M3GNetRelaxMaker workflows, but both seem to experience all three of these outcomes.

I don't seem to recall `fit_elastic_tensor` fireworks to take ~1 hr in the past, is these a bug somewhere in `atomate2/common/schemas/elastic.py`?

### environment

installed with `pip install "atomate2[strict]"`

```
FireWorks                 2.0.3
jobflow                   0.1.14
atomate2                  0.0.12
pydantic                  2.4.2
pydantic_core             2.10.1
pydantic-settings         2.0.3
monty                     2023.9.25
```

**Comment by utf** [comment]
This is now fixed in version 0.1.14
